### PR TITLE
configure continous integration

### PR DESCRIPTION
**Pull request by Yassin-hagenimana**

### CODE REVIEW

**Review by veritem — CHANGES_REQUESTED** [review]
Yo, you're remaining with on task on your trello card. Testing app using github actions.

**Review by tuyishimejeandamour — COMMENTED** [review]
I think every thing is set as it should be

**Comment by veritem** [comment]
@Yassin-hagenimana  fix conflicts

**Comment by veritem** [comment]
sorry that was a mistake 🙏

**Comment by veritem** [comment]
@Yassin-hagenimana fix conflicts

**Comment by Yassin-hagenimana** [comment]
done

**Review by veritem — APPROVED** [review]

**Review by Muhodari — APPROVED** [review]

**Review by tuyishimejeandamour — APPROVED** [review]

**Pull request merged**
